Issue 4 user can delete their entries
james-aguirre/code-journal pull request #8
Opened 2023-04-17 18:38 UTC by james-aguirre

![Screenshot 2023-04-17 at 11 37 00 AM](https://user-images.githubusercontent.com/121325991/232580313-a36b4c74-3db8-4745-b256-0a07f1673e4a.png)
![Screenshot 2023-04-17 at 11 36 33 AM](https://user-images.githubusercontent.com/121325991/232580325-251bcf3a-707b-4a17-b84d-ebb92317b8e0.png)

2023-04-17 20:49 UTC, james-aguirre commented
![Kapture 2023-04-17 at 13 48 06](https://user-images.githubusercontent.com/121325991/232607488-810b6608-0410-47fd-bbf2-8cbfe3fbc01b.gif)

2023-04-18 18:42 UTC, james-aguirre commented
![Kapture 2023-04-18 at 11 40 31](https://user-images.githubusercontent.com/121325991/232873075-374ef264-a6d8-490a-92e0-a86838a7efe1.gif)

2023-04-19 18:05 UTC, shawnkost requested changes
A few changes here James!

2023-04-19 18:05 UTC, shawnkost commented on css/styles.css
> +  font-size: 1rem;
There shouldn't be a need for using such large `rem` values, if you're using such large values, you're probably doing something "hacky" to get this to work. You shouldn't be needing to use width & height alongside offset values. You should be using one or the other. Revisiting `javascript-modal` would be a good exercise for this

Your modal should be split into 2. The outer div / parent div controls where it appears on the page. And then inside of that, you should have another div where all the content belongs.

2023-04-19 18:05 UTC, shawnkost commented on js/main.js
> +  viewSwap('entries');
This should be `data.view`. You don't want to swap to a specific page, you want to utilize whatever was stored on your last refresh

2023-04-19 18:05 UTC, shawnkost commented on js/main.js
> +  $formHeader.classList.add('opacity');
There shouldn't be a need to give so many different elements a class of `opacity` or dark to apply the filter on them. You should just have a background color on your `modal` container, and that will impact everything

2023-04-19 18:05 UTC, shawnkost commented on js/main.js
> +}
Same note as above ^

2023-04-19 18:05 UTC, shawnkost commented on js/main.js
> +  $saveButton.classList.remove('opacity');
Same note above ^

2023-04-20 17:30 UTC, james-aguirre commented
<img width="635" alt="Screenshot 2023-04-20 at 10 28 56 AM" src="https://user-images.githubusercontent.com/121325991/233443306-3bfc1930-4927-42bf-b7cd-6b41b7196f51.png">

2023-04-24 16:27 UTC, shawnkost approved these changes
👍🏻

2023-04-24 16:39 UTC, merged